# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 4
create_project -in_memory -part xc7k160tffg676-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/15390/Desktop/DD/Mylab/lab9/MyLATCHS/MyLATCHS.cache/wt [current_project]
set_property parent.project_path C:/Users/15390/Desktop/DD/Mylab/lab9/MyLATCHS/MyLATCHS.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/15390/Desktop/DD/Mylab/lab9/MyLATCHS/MyLATCHS.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/15390/Desktop/DD/Mylab/lab9/MyLATCHS/MyLATCHS.srcs/sources_1/imports/circuit/CSR_LATCH.v
  C:/Users/15390/Desktop/DD/Mylab/lab9/MyLATCHS/MyLATCHS.srcs/sources_1/imports/Untitled_2/D_FLIPFLOP/verilog/circuit/D_FLIPFLOP.v
  C:/Users/15390/Desktop/DD/Mylab/lab9/MyLATCHS/MyLATCHS.srcs/sources_1/imports/Untitled_2/D_LATCH/verilog/circuit/D_LATCH.v
  C:/Users/15390/Desktop/DD/Mylab/lab9/MyLATCHS/MyLATCHS.srcs/sources_1/imports/lab9/LEDP2S_IO.v
  C:/Users/15390/Desktop/DD/Mylab/lab9/MyLATCHS/MyLATCHS.srcs/sources_1/imports/Untitled_2/MS_FLIPFLOP/verilog/circuit/MS_FLIPFLOP.v
  C:/Users/15390/Desktop/DD/Mylab/lab9/MyLATCHS/MyLATCHS.srcs/sources_1/imports/verilog/gates/NAND_GATE.v
  C:/Users/15390/Desktop/DD/Mylab/lab9/MyLATCHS/MyLATCHS.srcs/sources_1/imports/Untitled_2/D_FLIPFLOP/verilog/gates/NAND_GATE_3_INPUTS.v
  C:/Users/15390/Desktop/DD/Mylab/lab9/MyLATCHS/MyLATCHS.srcs/sources_1/new/clkdiv_pulse.v
  C:/Users/15390/Desktop/DD/Mylab/lab9/MyLATCHS/MyLATCHS.srcs/sources_1/imports/new/pbdebounce.v
  C:/Users/15390/Desktop/DD/Mylab/lab9/MyLATCHS/MyLATCHS.srcs/sources_1/new/Top.v
}
read_edif C:/Users/15390/Desktop/DD/Mylab/lab9/MyLATCHS/MyLATCHS.srcs/sources_1/imports/lab9/LEDP2S.ngc
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/15390/Desktop/DD/Mylab/lab9/MyLATCHS/MyLATCHS.srcs/constrs_1/new/L9.xdc
set_property used_in_implementation false [get_files C:/Users/15390/Desktop/DD/Mylab/lab9/MyLATCHS/MyLATCHS.srcs/constrs_1/new/L9.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Top -part xc7k160tffg676-2L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_utilization_synth.rpt -pb Top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
